name: RDP

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Enable RDP Access
        run: |
          net user runneradmin MyStrongPassword123 /add
          net localgroup administrators runneradmin /add
          Enble-computerRestors -Drive "C:\"
          vssadmin resize shadowstore /for=C: /on=C /MaxSize=10% 
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name 'fDenyTSConnections' -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
      - name: Keep ALive for 6 Hours
        run: |
          for /1 %%x in (1, 1, 360) do (
            echo Running %%x...
            timeout /t 60
          )
